export const CREATE_LEAGUE = "@@leagues/CREATE_LEAGUE";
export const CREATE_LEAGUE_SUCCESS = "@@leagues/CREATE_LEAGUE_SUCCESS";
export const CREATE_LEAGUE_FAILURE = "@@leagues/CREATE_LEAGUE_FAILURE";

export const FETCH_LEAGUES = "@@leagues/FETCH_LEAGUES";
export const FETCH_LEAGUES_SUCCESS = "@@leagues/FETCH_LEAGUES_SUCCESS";
export const FETCH_LEAGUES_FAILURE = "@@leagues/FETCH_LEAGUES_FAILURE";

export const FETCH_LEAGUE_DETAILS = "@@leagues/FETCH_LEAGUE_DETAILS";
export const FETCH_LEAGUE_DETAILS_SUCCESS = "@@leagues/FETCH_LEAGUE_DETAILS_SUCCESS";
export const FETCH_LEAGUE_DETAILS_FAILURE = "@@leagues/FETCH_LEAGUE_DETAILS_FAILURE";
