export const FETCH_CREATE_MATCH_INFO = "@@matches/FETCH_CREATE_MATCH_INFO";
export const FETCH_CREATE_MATCH_INFO_SUCCESS = "@@matches/FETCH_CREATE_MATCH_INFO_SUCCESS";
export const FETCH_CREATE_MATCH_INFO_FAILURE = "@@matches/FETCH_CREATE_MATCH_INFO_FAILURE";
