export const CREATE_MATCH = "@@matches/CREATE_MATCH";
export const CREATE_MATCH_SUCCESS = "@@matches/CREATE_MATCH_SUCCESS";
export const CREATE_MATCH_FAILURE = "@@matches/CREATE_MATCH_FAILURE";

export const FETCH_CREATE_MATCH_INFO = "@@matches/FETCH_CREATE_MATCH_INFO";
export const FETCH_CREATE_MATCH_INFO_SUCCESS = "@@matches/FETCH_CREATE_MATCH_INFO_SUCCESS";
export const FETCH_CREATE_MATCH_INFO_FAILURE = "@@matches/FETCH_CREATE_MATCH_INFO_FAILURE";
